In [1]:
import torch
import numpy

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.size()

torch.Size([12])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.size(0) ==x.shape[0]

True

In [6]:
x.reshape(3,4) #等价于 x.reshape(-1,4) x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x.reshape(-1,1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

In [8]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.randn(4,4)

tensor([[ 2.3072,  1.5488, -0.6974,  0.0421],
        [ 0.9387,  0.9062, -0.1646, -0.2749],
        [-0.2960,  0.0195,  0.3856, -1.5140],
        [-1.2942,  0.6563, -1.1841,  1.4349]])

In [10]:
x = torch.tensor([1.0,2,4,8]) 
y = torch.tensor([2,2,2,2])
x + y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim = 0),torch.cat((X,Y),dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [15]:
a = torch.tensor([[[i for i in [2,2,2]] for i in range(1)] for i in range(2)])
b = torch.tensor([[[i for i in [1,1,1]] for i in range(2)] for i in range(1)] )
print(a.shape,b.shape)
a + b

torch.Size([2, 1, 3]) torch.Size([1, 2, 3])


tensor([[[3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3]]])

In [16]:
X[1,2],X[1][2]

(tensor(6.), tensor(6.))

In [17]:
X[0:2,:]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [18]:
X[0:2][:]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [19]:
#其实就是numpy的切片操作，原本的元组也可以索引x[1,2],=多维切片x[0:2][:]
x = [[0., 1., 2., 3.],[4., 5., 9., 7.]]
x[0:2][:]
#x[0:2,0:1]

[[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 9.0, 7.0]]

In [20]:
x = numpy.array([[0., 1., 2., 3.],[4., 5., 9., 7.]])
x[0:2,:]

array([[0., 1., 2., 3.],
       [4., 5., 9., 7.]])

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
print(Z)

id(Z): 140454110024464
id(Z): 140454110024464
tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])


2.1.6. 转换为其他Python对象

将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。 torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量。

In [22]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。

In [23]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

2.1.7. 小结
深度学习存储和操作数据的主要接口是张量（n维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。

In [24]:
X*Y

tensor([[ 0.,  1.,  8.,  9.],
        [ 4., 10., 18., 28.],
        [32., 27., 20., 11.]])